# Generated by Django 6.0.4 on 2026-05-02 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_employerprofile_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employerprofile',
            name='location',
        ),
    ]
